apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster2
 annotations:
   volume.beta.kubernetes.io/storage-class: glusterfs
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 20Gi
